name: Tests

on:
  push:

permissions:
  contents: read

jobs:
  acceptance:
    environment: Test
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.2.*'
          terraform_wrapper: false
      - name: Run acceptance tests
        run: make testacc
        env:
          OPAL_TEST_TOKEN: ${{ secrets.OPAL_TEST_TOKEN }}
          OPAL_TEST_KNOWN_USER_ID_1: ${{ secrets.OPAL_TEST_KNOWN_USER_ID_1 }}
          OPAL_TEST_KNOWN_USER_ID_2: ${{ secrets.OPAL_TEST_KNOWN_USER_ID_2 }}
          OPAL_TEST_BASE_URL: ${{ secrets.OPAL_TEST_BASE_URL }}
          OPAL_TEST_KNOWN_CUSTOM_APP_ID: ${{ secrets.OPAL_TEST_KNOWN_CUSTOM_APP_ID }}
          OPAL_TEST_KNOWN_CUSTOM_APP_ADMIN_OWNER_ID: ${{ secrets.OPAL_TEST_KNOWN_CUSTOM_APP_ADMIN_OWNER_ID }}
          OPAL_TEST_KNOWN_REQUEST_TEMPLATE_ID: ${{ secrets.OPAL_TEST_KNOWN_REQUEST_TEMPLATE_ID }}
      - name: Clean up test organization
        run: make sweep
        env:
          OPAL_TEST_TOKEN: ${{ secrets.OPAL_TEST_TOKEN }}
          OPAL_TEST_KNOWN_USER_ID_1: ${{ secrets.OPAL_TEST_KNOWN_USER_ID_1 }}
          OPAL_TEST_KNOWN_USER_ID_2: ${{ secrets.OPAL_TEST_KNOWN_USER_ID_2 }}
          OPAL_TEST_BASE_URL: ${{ secrets.OPAL_TEST_BASE_URL }}
          OPAL_TEST_KNOWN_CUSTOM_APP_ID: ${{ secrets.OPAL_TEST_KNOWN_CUSTOM_APP_ID }}
          OPAL_TEST_KNOWN_CUSTOM_APP_ADMIN_OWNER_ID: ${{ secrets.OPAL_TEST_KNOWN_CUSTOM_APP_ADMIN_OWNER_ID }}
          OPAL_TEST_KNOWN_REQUEST_TEMPLATE_ID: ${{ secrets.OPAL_TEST_KNOWN_REQUEST_TEMPLATE_ID }}
      - name: Generate docs
        run: go generate
      - name: Check for doc changes
        id: check-changes
        uses: mskri/check-uncommitted-changes-action@v1.0.1
      - name: Fail if docs changed
        if: steps.check-changes.outputs.outcome == failure()
        run: echo "There are uncommitted changes"
